### ISSUE TITLE
peyotl, status of; and Open Tree of Life APIs

### ISSUE THREAD

**Issue by karolisr** [OpenTreeOfLife/hackathon#27]
I have finally had some time to dig into the available tools and being mostly a Python programmer peyotl seems to be something I can contribute to the most. What is the status of peyotl and version 2 of the APIs?

https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs

I would like to work on a set of methods that would allow users to have a clear access to OTOL APIs using Python. I am going through peyotl source code at the moment, but it isn't quite clear to me how different pieces interconnect and exactly what the scope of the peyotl project is.

If someone could list what peyotl can and cannot do at the moment and what features are needed that would be great.

**Comment by mtholder** [comment]
Peyotl has wrappers around many of the services of the open tree of life APIs. Right now those wrappers make calls the version 1 API. But there is not really much you can do with v2 that you couldn't due with v1 (v2 is just more consistent).  So that is not really limiting. Now that v2 is deployed, I'll start to transition the api wrappers around to using them.

The code that I'd expect most python code using peyotl to concentrate on is in peyotl/api. Right now it may be easiest to look at the code in peyotl/test/test_phylesystem_api.py, peyotl/test/test_oti.py, peyotl/test/test_taxomachine.py, and peyotl/test/test_treemachine.py
I'll try to work on the peyotl wiki today to add documentation for those methods.

peyotl's other goal is to provide a library for dealing with the data models used in open tree. Because it does this, it is used on the server-side (by both the phylesystem-api by the study curation tool's study import features [code for that is in opentree repo in the subdir: curator/controllers/default.py]). So the use of peyotl on both the server and client side make it quite a bit bulkier than one would expect for a client side library.

**Comment by mtholder** [comment]
I have not gotten around to documenting the treemachine wrapper, but I have some docs of the other wrappers (starting at https://github.com/OpenTreeOfLife/peyotl/wiki/api-wrappers ).
I've also tried to add a TODO to each page about work on that wrapper that needs to be done.

Also some simple examples in the examples dir on this branch: https://github.com/OpenTreeOfLife/peyotl/tree/cleanup

**Comment by mtholder** [comment]
I still haven't finished the docs on the treemachine wrappers, but I was a bit too optimistic in my first response: there are several new functions in the `taxonomy/` URLs to be wrapped (they did not have analogues in v1).

**Comment by mtholder** [comment]
"Roadmap" is probably too strong a word for this page, but there are also some TODOs on https://github.com/OpenTreeOfLife/peyotl/wiki/roadmap
