### ISSUE TITLE
Integrate Global Biotic Interactions with OpenTree

### ISSUE THREAD

**Issue by jhpoelen** [OpenTreeOfLife/hackathon#9]
I was hoping to pair up with evolution biologists, paleontologists and/or ecologists during the OpenTreeOfLife hack-a-thon to answer questions that relate how species interact (predator-prey, parasite-host, pollinator-plant) to how species evolved. For instance, what are some common ancestors of prey items of King Mackerel (_Scomberomorus cavalla_) and how are they related? 

I suspect that some of these types of questions can be answered by integrating http://globalbioticinteractions.org with http://opentreeoflife.org . Given the pretty nice tools that opentree provides, this should not be too much of a technical challenge. Finding a good question however . . . 

Curious to hear your thoughts! 

Perhaps @jsimons9, @hlapp, @cmungall , @jhammock , @cparr , @proopnarine or @BrianHayden have some ideas . . .

**Comment by proopnarine** [comment]
I think that's a pretty fascinating question. It should be doable with larger food webs since they tend to have multiple closely related species, or across communities as suggested using the global database. So what do we do?

Peter

Dr. Peter D. Roopnarine, Curator of Geology
Chair, Department of Invertebrate Zoology & Geology
Institute for Biodiversity Science and Sustainability
California Academy of Sciences
55 Music Concourse Drive
Golden Gate Park
San Francisco CA 94118

Phone: (415) 379-5271
FAX: (415) 379-5732
WWW: http://zeus.calacademy.org/roopnarine/peter.html
Blogs: http://www.calacademy.org/blogs/
http://proopnarine.wordpress.com
"If I could explain it to the average person, I wouldn't have been worth the Nobel Prize", R. Feynman
http://www.brainyquote.com/quotes/quotes/r/richardpf116607.html

**Comment by jhpoelen** [comment]
@proopnarine : thanks for commenting. we'd need to pair up with an evolutionary biologist to form a specific, relevant question. I guess we are looking for a reason to build a neat toy. . . However, I feel that without such a reason, it would be easy to build something that might not be as useful as intended.

**Comment by jhpoelen** [comment]
See example in #13 and https://github.com/jhpoelen/eol-globi-data/issues/87 for examples of an early integration between GloBI and OpenTree.

**Comment by jhpoelen** [comment]
Please see https://github.com/lukejharmon/traitathon/wiki/Pocket-Gophers-and-Their-Parasitic-Chewing-Lice for  a specific example on how to integrate GloBI interaction data with Open Tree of Life phylogenetic trees. Please re-open issue if you'd like to share thoughts or have questions.
